### ISSUE TITLE
No data file in r code was found.

### ISSUE THREAD

**Issue by HaomiaoLuoLlanio** [dbgoodman/tcsl-lenti#1]
Hi, 
I am trying to reimplement the code. However, I can't find the data files and directories in your code. Could you please give me some hints to run them? Thank you!

**Comment by dbgoodman** [comment]
Hello,

As noted in the manuscript, all of the data is here: https://zenodo.org/record/7063644

I will put this link in the README so it is more clear. Thanks for your interest!
